fix NoSuchMethodError on older java versions (1.8)
Caused by: java.lang.NoSuchMethodError:
java.util.List.toArray(Ljava/util/function/IntFunction;)[Ljava/lang/Object;